services:
  # More info at https://github.com/oracle/opengrok/docker/
  opengrok:
    container_name: opengrok
    image: pkemb/opengrok:1.14.3
    entrypoint: [ "/bin/sh", "/opengrok/entrypoint.sh" ]
    ports:
      - "8080:8080"
      - "8000:8000"
    environment:
      SYNC_PERIOD_MINUTES: 0
      OPENGROK_VERBOSE: true
      NOMIRROR: "yes"
      REST_PORT: 8000
      REST_TOKEN: ${OPENGROK_REST_TOKEN}
      INDEXER_OPT: "-S" # scan nested repos from /opengrok/src path
      READONLY_CONFIG_FILE: /opengrok/etc/read_only.xml
      OPENGROK_PROJECT_GROUP_NAME: ${OPENGROK_PROJECT_GROUP_NAME}
      JAVA_OPTS: "-Xms2g -Xmx4g"
    volumes:
      - ./opengrok/data:/opengrok/data
      - ./opengrok/src:/opengrok/src
      - ./opengrok/etc:/opengrok/etc
      - ./opengrok/entrypoint.sh:/opengrok/entrypoint.sh:ro
  mimir-syncer:
    build: ./syncer
    container_name: mimir-syncer
    restart: unless-stopped
    environment:
      - GIT_PROVIDER=${GIT_PROVIDER} # github or bitbucket
      - API_TOKEN=${API_TOKEN}
      - ORG_NAME=${ORG_NAME}
      - SYNC_INTERVAL=3600
      - REPOS_DIR=/opengrok/src
      - SYNC_BRANCH_PRIORITY=${SYNC_BRANCH_PRIORITY}
      - OPENGROK_REST_TOKEN=${OPENGROK_REST_TOKEN}
    volumes:
      - ./opengrok/src:/opengrok/src
